### ISSUE TITLE
Adding SearXNG as search engine in Firefox Android fails

### ISSUE THREAD

**Issue by utzer** [YunoHost-Apps/searxng_ynh#173]
When I try to add SearXNG as a search engine in Firefox (latest version) for Android it fails. It immediately states that 'name' could not be connected, "Error when connecting to utzer" or so. 

This is the fault in German. 
![Screenshot_20231210_142619_Firefox](https://github.com/YunoHost-Apps/searxng_ynh/assets/8361662/b287c305-2f6a-49e7-a97a-0eecaac392f1)

The SearXNG Appication is installed and available publicly, but I guess something of Yunohost is interfering the connection. 

Same happens when I add it with a short URL that does not contain the search settings. 

It works when I get a random SearXNG instance URL, but I'd like to use mine instead. 

Any way to trick Firefox to allow it to add the search engine? Or maybe even a solution to the problem?

**Comment by mh4ckt3mh4ckt1c4s** [comment]
Hi, thanks for your report. I experimented the same problem with my instance and Firefox Android, but when I debugged it I thought is was a Firefox bug related to my url being too long. If you have the problem too I'd like to debug with your instance too to see if they are the same problems. 
A few questions : 
- Did you already manage to add your instance as a search engine elsewhere (e.g., in Firefox on PC) ?
- Do you mind sharing the exact url you tried to input into the configuration of Firefox Android ?

**Comment by utzer** [comment]
> thought is was a Firefox bug related to my url being too long.
I thought that too, but it is not I assume. 




> * Did you already manage to add your instance as a search engine elsewhere (e.g., in Firefox on PC) ?

Firefox Linux using at as standard search engine, no problem when I added it, but the process is different, it uses Open Search or something like that. 

> * Do you mind sharing the exact url you tried to input into the configuration of Firefox Android ?

Would prefer not to share it publicly, one week life time [here](https://zerobin.utzer.de/?68fb87b49ae181a2#6PSDAFty3ZLgf1ePit12EqwoZ32d3La5BbCt21z1LDEW) it is.
Password: SearXNG

Had a public instance before, it got overloaded often after the URL was linked in some places. 

So basic info from that zerobin, I tried the long URL that contained the whole search config, but I also tried the short URL that is `https://search.example.com/searxng/search?q=%s`, which also didn't work. So I think it is not the URL length. 

Also I tried another public SearXNG with the long link and it worked and still works to add it again in FF Android.

**Comment by mh4ckt3mh4ckt1c4s** [comment]
Thanks for sharing your config. I investigated again and found out that the error is the same for my and your site, so this is indeed YNH-related.

What is strange is, I debugged Firefox Android to find what's wrong, and when the query is made to add the search engine, Firefox seems to throw an error named `SSL_ERROR_PROTOCOL_VERSION_ALERT`. This makes me think that it is a bug on Firefox's side as the YNH SSL/TLS configuration is surely correct and works in most cases. Furthermore, adding the YNH SearXNG engines on Firefox desktop, even with the "%s" method (that can be made available in advances settings), is working.

However, the bug should be fixable on YNH side (YNH core though, as it is in YNH core that the SSL/TLS termination is handled I guess). We "just" need to understand which TLS parameters needs to be modified for Firefox Android no to throw an error, assuming this is indeed TLS-related. My current debugging setup does not allow me to inspect TLS traffic, so I will try again later with decrypting traffic and taking a look at the TLS handshake.

**Comment by utzer** [comment]
Thanks, let me know if I can help with looking into some log on the server or something like that.

**Comment by mh4ckt3mh4ckt1c4s** [comment]
Finally found the "bug"! Thing is, YunoHost is configured to accept TLSv1.3 only. And for some reason, Firefox does not (attempt to) use TLSv1.3 but only TLSv1.2... Which makes YNH refuse the connection. 

A workaround on YNH side is to modify the nginx configuration to let it accept TLSv1.2. For this you have two ways : 
- Using YNH options (easy way, but didn't work for me) : in the admin panel, go to Tools > YunoHost settings > NGINX (web server) and switch the nginx compatibility from Modern to Intermediate. This should enable TLSv1.2 and make the bug disappear. You can see what the different options do with [this file](https://github.com/YunoHost/yunohost/blob/dev/conf/nginx/security.conf.inc). Changing the option in the admin panel did not work for me because YNH told me that *The configuration file '/etc/nginx/conf.d/security.conf.inc' has been manually modified and will not be updated*, which I effectively did when experimenting on the bug. If you try this option please let me know how it went for you.
- Patching the file yourself : ssh on your server as root, then edit the file at `/etc/nginx/conf.d/security.conf.inc` and change the line 
```
ssl_protocols TLSv1.3;
```
To 
```
ssl_protocols TLSv1.3 TLSv1.2;
```
then restart your nginx server with `nginx -s reload`. This did the trick for me.

To check if your server is currently supporting (or not) TLSv1.2, you can use this site : https://www.ssllabs.com/ssltest

I'll conclude this by saying this is more a bug on Firefox's side IMO. Firefox in its latest version should definitely not be stuck on not supporting TLSv1.3, even for some advanced options. I'll make a report to Firefox when I find the time and I will put the link here once posted.

**Comment by mh4ckt3mh4ckt1c4s** [comment]
Bug to Firefox reported [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1876607)

**Comment by utzer** [comment]
> * Using YNH options (easy way, but didn't work for me) : in the admin panel, go to Tools > YunoHost settings > NGINX (web server) and switch the nginx compatibility from Modern to Intermediate.

This worked for me! Amazing that you figured this out!

**Comment by mh4ckt3mh4ckt1c4s** [comment]
Happy to help. According to the bug report in Firefox, this is gonna be fixed in Firefox 124, which should be released on March 19, 2024. You would try to set your settings back to "Modern" then and see if it works. I'm gonna close this but feel free to reopen if you still encounter the bug with FF 124.
